#!/usr/bin/env bash
# command to install nginx on the web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

# testing nginx configurations
sudo nginx -t

sudo service nginx reload
